name: CI + Docker Publish

on:
  push:
    branches: [ main ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout code
        uses: actions/checkout@v4

      # Node tests (optional)
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install & test
        run: |
          npm ci
          npm test || echo "no tests yet"

      # Build Docker image
      - name: Build Docker image
        run: docker build -t mohan1266/hello-node:latest .

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push image to Docker Hub
      - name: Push image
        run: docker push mohan1266/hello-node:latest
